### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by sheri-thomson** [sheri-thomson/exploding-robot-head#1]
@thomasjbradley

Before adding 
```
.robot-head-right {
  float:right;
}

.robot-head-left {
  float: left;
}
```
...the website looked better, but each of the above elements were in the wrong place.

**Comment by sheri-thomson** [comment]
like, how do I get the brain to line up properly? And is the z-index I added incorrect? I wanted to put it in front of the body but behind the two head parts..

**Comment by thomasjbradley** [comment]
Some changes to make:

- Remove everything `float`—only use position
- Remove `absolute` from `.robot-body`
- Add `position: relative` to `.robot`
- The two head and brain pieces should all be `absolute`

**Comment by sheri-thomson** [comment]
Thanks! I'll have to rewatch the videos again because I really don't understand how to do this ..
It'll be my third go at the videos.  I've tried playing around with different formulas but nothing seems to be moving those pieces. I thought I was kinda close until removing all that css ..now they're not centred or even on top of the body..The last assignment took me hours and I can't even make sense of it. I'm also referring to cheat sheets and previous code but to no avail. Maybe I need to step away for a bit..

**Comment by sheri-thomson** [comment]
can't. step. away.
need. to. under-stand.
(said in robot accent)

**Comment by sheri-thomson** [comment]
@thomasjbradley 
Okay, so I figured out a how to get it to a point where I can now move on to styling the hover element.
Before I move forward, is there an alternate way of getting to this point, or did I get there the right way?

**Comment by thomasjbradley** [comment]
That looks good to me.

The only thing I would remove is the `transform` from the head pieces. The aren't being centered so they `transform` is unnecessary. That would then simplify their `left` & `right` coordinates instead of being weird, random numbers.

**Comment by sheri-thomson** [comment]
Thank you
